2018-07-11 13:52:10,158 ERROR: Exception on /index [GET] [in c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Charly\python\CFDIsWeb\webapp\routes.py", line 55, in index
    return render_template('index.html', title='Inicio', serv=True, form=frmss)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\base.html", line 58, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\index.html", line 39, in block "app_content"
    {{ url_for("es_lg.json") }}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'es_lg.json'. Did you mean 'reset_password' instead?
2018-07-11 13:53:56,715 INFO: Email Robot iniciado [in C:\Users\Charly\python\CFDIsWeb\webapp\__init__.py:33]
2018-07-11 13:54:04,969 ERROR: Exception on /index [GET] [in c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Charly\python\CFDIsWeb\webapp\routes.py", line 56, in index
    return render_template('index.html', title='Inicio', serv=True, form=frmss)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\base.html", line 58, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Charly\python\CFDIsWeb\webapp\templates\index.html", line 39, in block "app_content"
    {{ url_for("es_lg.json") }}
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "c:\users\charly\python\cfdisweb\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'es_lg.json'. Did you mean 'reset_password' instead?
2018-07-11 13:55:54,563 INFO: Email Robot iniciado [in C:\Users\Charly\python\CFDIsWeb\webapp\__init__.py:33]
